package com.edexer.model;

// Generated May 2, 2015 10:45:02 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdminConfigId generated by hbm2java
 */
@Embeddable
public class AdminConfigId implements java.io.Serializable {

	private String configKeyName;
	private String configValue;

	public AdminConfigId() {
	}

	public AdminConfigId(String configKeyName, String configValue) {
		this.configKeyName = configKeyName;
		this.configValue = configValue;
	}

	@Column(name = "config_key_name", length = 100)
	public String getConfigKeyName() {
		return this.configKeyName;
	}

	public void setConfigKeyName(String configKeyName) {
		this.configKeyName = configKeyName;
	}

	@Column(name = "config_value", length = 150)
	public String getConfigValue() {
		return this.configValue;
	}

	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdminConfigId))
			return false;
		AdminConfigId castOther = (AdminConfigId) other;

		return ((this.getConfigKeyName() == castOther.getConfigKeyName()) || (this
				.getConfigKeyName() != null
				&& castOther.getConfigKeyName() != null && this
				.getConfigKeyName().equals(castOther.getConfigKeyName())))
				&& ((this.getConfigValue() == castOther.getConfigValue()) || (this
						.getConfigValue() != null
						&& castOther.getConfigValue() != null && this
						.getConfigValue().equals(castOther.getConfigValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getConfigKeyName() == null ? 0 : this.getConfigKeyName()
						.hashCode());
		result = 37
				* result
				+ (getConfigValue() == null ? 0 : this.getConfigValue()
						.hashCode());
		return result;
	}

}
