package com.edexer.model;

// Generated Apr 19, 2015 8:37:20 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BcRequestStatus generated by hbm2java
 */
@Entity
@Table(name = "bc_request_status", catalog = "edexer")
public class BcRequestStatus implements java.io.Serializable {

	private Integer statusId;
	private String statusName;
	private String desc;
	private Set bcRequests = new HashSet(0);

	public BcRequestStatus() {
	}

	public BcRequestStatus(String statusName, String desc, Set bcRequests) {
		this.statusName = statusName;
		this.desc = desc;
		this.bcRequests = bcRequests;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "status_id", unique = true, nullable = false)
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "status_name", length = 50)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "desc", length = 50)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bcRequestStatus")
	public Set getBcRequests() {
		return this.bcRequests;
	}

	public void setBcRequests(Set bcRequests) {
		this.bcRequests = bcRequests;
	}

}
