package com.edexer.model;

// Generated May 2, 2015 10:45:02 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FaxId generated by hbm2java
 */
@Embeddable
public class FaxId implements java.io.Serializable {

	private int bcId;
	private String faxNum;

	public FaxId() {
	}

	public FaxId(int bcId, String faxNum) {
		this.bcId = bcId;
		this.faxNum = faxNum;
	}

	@Column(name = "bc_id", nullable = false)
	public int getBcId() {
		return this.bcId;
	}

	public void setBcId(int bcId) {
		this.bcId = bcId;
	}

	@Column(name = "fax_num", nullable = false, length = 50)
	public String getFaxNum() {
		return this.faxNum;
	}

	public void setFaxNum(String faxNum) {
		this.faxNum = faxNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FaxId))
			return false;
		FaxId castOther = (FaxId) other;

		return (this.getBcId() == castOther.getBcId())
				&& ((this.getFaxNum() == castOther.getFaxNum()) || (this
						.getFaxNum() != null && castOther.getFaxNum() != null && this
						.getFaxNum().equals(castOther.getFaxNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBcId();
		result = 37 * result
				+ (getFaxNum() == null ? 0 : this.getFaxNum().hashCode());
		return result;
	}

}
