package com.edexer.model;

// Generated May 2, 2015 10:45:02 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImId generated by hbm2java
 */
@Embeddable
public class ImId implements java.io.Serializable {

	private String identifier;
	private int bcId;

	public ImId() {
	}

	public ImId(String identifier, int bcId) {
		this.identifier = identifier;
		this.bcId = bcId;
	}

	@Column(name = "identifier", nullable = false, length = 50)
	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	@Column(name = "bc_id", nullable = false)
	public int getBcId() {
		return this.bcId;
	}

	public void setBcId(int bcId) {
		this.bcId = bcId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImId))
			return false;
		ImId castOther = (ImId) other;

		return ((this.getIdentifier() == castOther.getIdentifier()) || (this
				.getIdentifier() != null && castOther.getIdentifier() != null && this
				.getIdentifier().equals(castOther.getIdentifier())))
				&& (this.getBcId() == castOther.getBcId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdentifier() == null ? 0 : this.getIdentifier()
						.hashCode());
		result = 37 * result + this.getBcId();
		return result;
	}

}
