package com.edexer.model;

// Generated May 2, 2015 10:45:02 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LastEditReason generated by hbm2java
 */
@Entity
@Table(name = "last_edit_reason", catalog = "edexer")
public class LastEditReason implements java.io.Serializable {

	private Integer reasonId;
	private String reasonName;
	private String desc;
	private Set userSubscriptions = new HashSet(0);

	public LastEditReason() {
	}

	public LastEditReason(String reasonName) {
		this.reasonName = reasonName;
	}

	public LastEditReason(String reasonName, String desc, Set userSubscriptions) {
		this.reasonName = reasonName;
		this.desc = desc;
		this.userSubscriptions = userSubscriptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "reason_id", unique = true, nullable = false)
	public Integer getReasonId() {
		return this.reasonId;
	}

	public void setReasonId(Integer reasonId) {
		this.reasonId = reasonId;
	}

	@Column(name = "reason_name", nullable = false, length = 50)
	public String getReasonName() {
		return this.reasonName;
	}

	public void setReasonName(String reasonName) {
		this.reasonName = reasonName;
	}

	@Column(name = "desc", length = 50)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lastEditReason")
	public Set getUserSubscriptions() {
		return this.userSubscriptions;
	}

	public void setUserSubscriptions(Set userSubscriptions) {
		this.userSubscriptions = userSubscriptions;
	}

}
