package com.edexer.model;

// Generated May 2, 2015 10:45:02 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MailConfig generated by hbm2java
 */
@Entity
@Table(name = "mail_config", catalog = "edexer", uniqueConstraints = @UniqueConstraint(columnNames = "user_id"))
public class MailConfig implements java.io.Serializable {

	private Integer mailConfigId;
	private User user;
	private String fromEmail;
	private String fromEmailPassword;
	private String encryptionType;
	private String outgoingMailServer;
	private int portNumber;
	private Boolean authentication;
	private Integer timeOut;

	public MailConfig() {
	}

	public MailConfig(User user, String fromEmail, String fromEmailPassword,
			String encryptionType, String outgoingMailServer, int portNumber) {
		this.user = user;
		this.fromEmail = fromEmail;
		this.fromEmailPassword = fromEmailPassword;
		this.encryptionType = encryptionType;
		this.outgoingMailServer = outgoingMailServer;
		this.portNumber = portNumber;
	}

	public MailConfig(User user, String fromEmail, String fromEmailPassword,
			String encryptionType, String outgoingMailServer, int portNumber,
			Boolean authentication, Integer timeOut) {
		this.user = user;
		this.fromEmail = fromEmail;
		this.fromEmailPassword = fromEmailPassword;
		this.encryptionType = encryptionType;
		this.outgoingMailServer = outgoingMailServer;
		this.portNumber = portNumber;
		this.authentication = authentication;
		this.timeOut = timeOut;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mail_config_id", unique = true, nullable = false)
	public Integer getMailConfigId() {
		return this.mailConfigId;
	}

	public void setMailConfigId(Integer mailConfigId) {
		this.mailConfigId = mailConfigId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", unique = true, nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "from_email", nullable = false, length = 50)
	public String getFromEmail() {
		return this.fromEmail;
	}

	public void setFromEmail(String fromEmail) {
		this.fromEmail = fromEmail;
	}

	@Column(name = "from_email_password", nullable = false, length = 50)
	public String getFromEmailPassword() {
		return this.fromEmailPassword;
	}

	public void setFromEmailPassword(String fromEmailPassword) {
		this.fromEmailPassword = fromEmailPassword;
	}

	@Column(name = "encryption_type", nullable = false, length = 50)
	public String getEncryptionType() {
		return this.encryptionType;
	}

	public void setEncryptionType(String encryptionType) {
		this.encryptionType = encryptionType;
	}

	@Column(name = "outgoing_mail_server", nullable = false, length = 50)
	public String getOutgoingMailServer() {
		return this.outgoingMailServer;
	}

	public void setOutgoingMailServer(String outgoingMailServer) {
		this.outgoingMailServer = outgoingMailServer;
	}

	@Column(name = "port_number", nullable = false)
	public int getPortNumber() {
		return this.portNumber;
	}

	public void setPortNumber(int portNumber) {
		this.portNumber = portNumber;
	}

	@Column(name = "authentication")
	public Boolean getAuthentication() {
		return this.authentication;
	}

	public void setAuthentication(Boolean authentication) {
		this.authentication = authentication;
	}

	@Column(name = "time_out")
	public Integer getTimeOut() {
		return this.timeOut;
	}

	public void setTimeOut(Integer timeOut) {
		this.timeOut = timeOut;
	}

}
