package com.edexer.model;

// Generated May 2, 2015 10:45:02 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MobileId generated by hbm2java
 */
@Embeddable
public class MobileId implements java.io.Serializable {

	private int bcId;
	private String mobileNum;

	public MobileId() {
	}

	public MobileId(int bcId, String mobileNum) {
		this.bcId = bcId;
		this.mobileNum = mobileNum;
	}

	@Column(name = "bc_id", nullable = false)
	public int getBcId() {
		return this.bcId;
	}

	public void setBcId(int bcId) {
		this.bcId = bcId;
	}

	@Column(name = "mobile_num", nullable = false, length = 20)
	public String getMobileNum() {
		return this.mobileNum;
	}

	public void setMobileNum(String mobileNum) {
		this.mobileNum = mobileNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MobileId))
			return false;
		MobileId castOther = (MobileId) other;

		return (this.getBcId() == castOther.getBcId())
				&& ((this.getMobileNum() == castOther.getMobileNum()) || (this
						.getMobileNum() != null
						&& castOther.getMobileNum() != null && this
						.getMobileNum().equals(castOther.getMobileNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBcId();
		result = 37 * result
				+ (getMobileNum() == null ? 0 : this.getMobileNum().hashCode());
		return result;
	}

}
