package com.edexer.model;

// Generated May 2, 2015 10:45:02 AM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mobile generated by hbm2java
 */
@Entity
@Table(name = "mobile", catalog = "edexer")
public class Mobile implements java.io.Serializable {

	private MobileId id;
	private BusinessCard businessCard;

	public Mobile() {
	}

	public Mobile(MobileId id, BusinessCard businessCard) {
		this.id = id;
		this.businessCard = businessCard;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bcId", column = @Column(name = "bc_id", nullable = false)),
			@AttributeOverride(name = "mobileNum", column = @Column(name = "mobile_num", nullable = false, length = 20)) })
	public MobileId getId() {
		return this.id;
	}

	public void setId(MobileId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bc_id", nullable = false, insertable = false, updatable = false)
	public BusinessCard getBusinessCard() {
		return this.businessCard;
	}

	public void setBusinessCard(BusinessCard businessCard) {
		this.businessCard = businessCard;
	}

}
