package com.edexer.model;

// Generated Feb 4, 2015 4:34:48 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sector generated by hbm2java
 */
@Entity
@Table(name = "sector", catalog = "edexer")
public class Sector implements java.io.Serializable {

	private Integer sectorId;
	private String sectorName;
	private String desc;
	private Set titles = new HashSet(0);

	public Sector() {
	}

	public Sector(String sectorName, String desc, Set titles) {
		this.sectorName = sectorName;
		this.desc = desc;
		this.titles = titles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sector_id", unique = true, nullable = false)
	public Integer getSectorId() {
		return this.sectorId;
	}

	public void setSectorId(Integer sectorId) {
		this.sectorId = sectorId;
	}

	@Column(name = "sector_name", length = 50)
	public String getSectorName() {
		return this.sectorName;
	}

	public void setSectorName(String sectorName) {
		this.sectorName = sectorName;
	}

	@Column(name = "desc", length = 50)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sector")
	public Set getTitles() {
		return this.titles;
	}

	public void setTitles(Set titles) {
		this.titles = titles;
	}

	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Sector))
            return false;
		if (this.getSectorId() == ((Sector) obj).getSectorId())
			return true;
		return false;
	}

}
