package com.edexer.model;

// Generated May 2, 2015 10:45:02 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SocialNetworksTypes generated by hbm2java
 */
@Entity
@Table(name = "social_networks_types", catalog = "edexer")
public class SocialNetworksTypes implements java.io.Serializable {

	private Integer snTypeId;
	private String name;
	private String desc;
	private Set socialNetworks = new HashSet(0);

	public SocialNetworksTypes() {
	}

	public SocialNetworksTypes(String name) {
		this.name = name;
	}

	public SocialNetworksTypes(String name, String desc, Set socialNetworks) {
		this.name = name;
		this.desc = desc;
		this.socialNetworks = socialNetworks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sn_type_id", unique = true, nullable = false)
	public Integer getSnTypeId() {
		return this.snTypeId;
	}

	public void setSnTypeId(Integer snTypeId) {
		this.snTypeId = snTypeId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "desc", length = 45)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "socialNetworksTypes")
	public Set getSocialNetworks() {
		return this.socialNetworks;
	}

	public void setSocialNetworks(Set socialNetworks) {
		this.socialNetworks = socialNetworks;
	}

}
