package com.edexer.model;

// Generated May 2, 2015 10:45:02 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", catalog = "edexer")
public class Tags implements java.io.Serializable {

	private Integer tagId;
	private UserSubscription userSubscription;
	private String tagName;
	private Set businessCards = new HashSet(0);

	public Tags() {
	}

	public Tags(UserSubscription userSubscription, String tagName) {
		this.userSubscription = userSubscription;
		this.tagName = tagName;
	}

	public Tags(UserSubscription userSubscription, String tagName,
			Set businessCards) {
		this.userSubscription = userSubscription;
		this.tagName = tagName;
		this.businessCards = businessCards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tag_id", unique = true, nullable = false)
	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "user_id", referencedColumnName = "user_id", nullable = false),
			@JoinColumn(name = "sub_type", referencedColumnName = "sub_type", nullable = false) })
	public UserSubscription getUserSubscription() {
		return this.userSubscription;
	}

	public void setUserSubscription(UserSubscription userSubscription) {
		this.userSubscription = userSubscription;
	}

	@Column(name = "tag_name", nullable = false, length = 50)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "bc_tags", catalog = "edexer", joinColumns = { @JoinColumn(name = "tags_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "bc_id", nullable = false, updatable = false) })
	public Set getBusinessCards() {
		return this.businessCards;
	}

	public void setBusinessCards(Set businessCards) {
		this.businessCards = businessCards;
	}

}
