package com.edexer.model;

// Generated May 2, 2015 10:45:02 AM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserSubscription generated by hbm2java
 */
@Entity
@Table(name = "user_subscription", catalog = "edexer")
public class UserSubscription implements java.io.Serializable {

	private UserSubscriptionId id;
	private User userBySubscriptionOwner;
	private SubscriptionStatus subscriptionStatus;
	private ActAs actAs;
	private LastEditReason lastEditReason;
	private User userByUserId;
	private User userByLastEditBy;
	private Subscription subscription;
	private Date startDate;
	private Date endDate;
	private Date subscriptionDate;
	private Date lastEditDate;
	private String note;
	private String isAdmin;
	private String canExport;
	private Set tagses = new HashSet(0);
	private Set businessCards = new HashSet(0);
	private Set bcPermissionses = new HashSet(0);

	public UserSubscription() {
	}

	public UserSubscription(UserSubscriptionId id,
			SubscriptionStatus subscriptionStatus, ActAs actAs,
			User userByUserId, Subscription subscription) {
		this.id = id;
		this.subscriptionStatus = subscriptionStatus;
		this.actAs = actAs;
		this.userByUserId = userByUserId;
		this.subscription = subscription;
	}

	public UserSubscription(UserSubscriptionId id,
			User userBySubscriptionOwner,
			SubscriptionStatus subscriptionStatus, ActAs actAs,
			LastEditReason lastEditReason, User userByUserId,
			User userByLastEditBy, Subscription subscription, Date startDate,
			Date endDate, Date subscriptionDate, Date lastEditDate,
			String note, String isAdmin, String canExport, Set tagses,
			Set businessCards, Set bcPermissionses) {
		this.id = id;
		this.userBySubscriptionOwner = userBySubscriptionOwner;
		this.subscriptionStatus = subscriptionStatus;
		this.actAs = actAs;
		this.lastEditReason = lastEditReason;
		this.userByUserId = userByUserId;
		this.userByLastEditBy = userByLastEditBy;
		this.subscription = subscription;
		this.startDate = startDate;
		this.endDate = endDate;
		this.subscriptionDate = subscriptionDate;
		this.lastEditDate = lastEditDate;
		this.note = note;
		this.isAdmin = isAdmin;
		this.canExport = canExport;
		this.tagses = tagses;
		this.businessCards = businessCards;
		this.bcPermissionses = bcPermissionses;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "subType", column = @Column(name = "sub_type", nullable = false)) })
	public UserSubscriptionId getId() {
		return this.id;
	}

	public void setId(UserSubscriptionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subscription_owner")
	public User getUserBySubscriptionOwner() {
		return this.userBySubscriptionOwner;
	}

	public void setUserBySubscriptionOwner(User userBySubscriptionOwner) {
		this.userBySubscriptionOwner = userBySubscriptionOwner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sub_status", nullable = false)
	public SubscriptionStatus getSubscriptionStatus() {
		return this.subscriptionStatus;
	}

	public void setSubscriptionStatus(SubscriptionStatus subscriptionStatus) {
		this.subscriptionStatus = subscriptionStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "act_as", nullable = false)
	public ActAs getActAs() {
		return this.actAs;
	}

	public void setActAs(ActAs actAs) {
		this.actAs = actAs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_edit_reason")
	public LastEditReason getLastEditReason() {
		return this.lastEditReason;
	}

	public void setLastEditReason(LastEditReason lastEditReason) {
		this.lastEditReason = lastEditReason;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUserByUserId() {
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_edit_by")
	public User getUserByLastEditBy() {
		return this.userByLastEditBy;
	}

	public void setUserByLastEditBy(User userByLastEditBy) {
		this.userByLastEditBy = userByLastEditBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sub_type", nullable = false, insertable = false, updatable = false)
	public Subscription getSubscription() {
		return this.subscription;
	}

	public void setSubscription(Subscription subscription) {
		this.subscription = subscription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "subscription_date", length = 10)
	public Date getSubscriptionDate() {
		return this.subscriptionDate;
	}

	public void setSubscriptionDate(Date subscriptionDate) {
		this.subscriptionDate = subscriptionDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_edit_date", length = 10)
	public Date getLastEditDate() {
		return this.lastEditDate;
	}

	public void setLastEditDate(Date lastEditDate) {
		this.lastEditDate = lastEditDate;
	}

	@Column(name = "note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "isAdmin", length = 1)
	public String getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(String isAdmin) {
		this.isAdmin = isAdmin;
	}

	@Column(name = "can_export", length = 1)
	public String getCanExport() {
		return this.canExport;
	}

	public void setCanExport(String canExport) {
		this.canExport = canExport;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userSubscription")
	public Set getTagses() {
		return this.tagses;
	}

	public void setTagses(Set tagses) {
		this.tagses = tagses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userSubscription")
	public Set getBusinessCards() {
		return this.businessCards;
	}

	public void setBusinessCards(Set businessCards) {
		this.businessCards = businessCards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userSubscription")
	public Set getBcPermissionses() {
		return this.bcPermissionses;
	}

	public void setBcPermissionses(Set bcPermissionses) {
		this.bcPermissionses = bcPermissionses;
	}

}
