package com.edexer.model;

// Generated May 3, 2015 11:11:40 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WebsiteMessageId generated by hbm2java
 */
@Embeddable
public class WebsiteMessageId implements java.io.Serializable {

	private String keyName;
	private String value;

	public WebsiteMessageId() {
	}

	public WebsiteMessageId(String keyName, String value) {
		this.keyName = keyName;
		this.value = value;
	}

	@Column(name = "key_name", length = 200)
	public String getKeyName() {
		return this.keyName;
	}

	public void setKeyName(String keyName) {
		this.keyName = keyName;
	}

	@Column(name = "value", length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WebsiteMessageId))
			return false;
		WebsiteMessageId castOther = (WebsiteMessageId) other;

		return ((this.getKeyName() == castOther.getKeyName()) || (this
				.getKeyName() != null && castOther.getKeyName() != null && this
				.getKeyName().equals(castOther.getKeyName())))
				&& ((this.getValue() == castOther.getValue()) || (this
						.getValue() != null && castOther.getValue() != null && this
						.getValue().equals(castOther.getValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKeyName() == null ? 0 : this.getKeyName().hashCode());
		result = 37 * result
				+ (getValue() == null ? 0 : this.getValue().hashCode());
		return result;
	}

}
