package com.edexer.model;

// Generated May 24, 2015 10:17:18 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActAs generated by hbm2java
 */
@Entity
@Table(name = "act_as", catalog = "edexer_edexer")
public class ActAs implements java.io.Serializable {

	private Integer actAsId;
	private String actAsName;
	private String desc;
	private Set userSubscriptions = new HashSet(0);

	public ActAs() {
	}

	public ActAs(String actAsName) {
		this.actAsName = actAsName;
	}

	public ActAs(String actAsName, String desc, Set userSubscriptions) {
		this.actAsName = actAsName;
		this.desc = desc;
		this.userSubscriptions = userSubscriptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "act_as_id", unique = true, nullable = false)
	public Integer getActAsId() {
		return this.actAsId;
	}

	public void setActAsId(Integer actAsId) {
		this.actAsId = actAsId;
	}

	@Column(name = "act_as_name", nullable = false, length = 50)
	public String getActAsName() {
		return this.actAsName;
	}

	public void setActAsName(String actAsName) {
		this.actAsName = actAsName;
	}

	@Column(name = "desc", length = 100)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actAs")
	public Set getUserSubscriptions() {
		return this.userSubscriptions;
	}

	public void setUserSubscriptions(Set userSubscriptions) {
		this.userSubscriptions = userSubscriptions;
	}

}
