package com.edexer.model;

// Generated May 24, 2015 10:17:18 AM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AdminConfig generated by hbm2java
 */
@Entity
@Table(name = "admin_config", catalog = "edexer_edexer")
public class AdminConfig implements java.io.Serializable {

	private AdminConfigId id;

	public AdminConfig() {
	}

	public AdminConfig(AdminConfigId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "configKeyName", column = @Column(name = "config_key_name", length = 100)),
			@AttributeOverride(name = "configValue", column = @Column(name = "config_value", length = 150)) })
	public AdminConfigId getId() {
		return this.id;
	}

	public void setId(AdminConfigId id) {
		this.id = id;
	}

}
