package com.edexer.model;

// Generated May 24, 2015 10:17:18 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "attachment", catalog = "edexer_edexer")
public class Attachment implements java.io.Serializable {

	private Integer attachmentId;
	private BusinessCard businessCard;
	private String path;
	private String description;

	public Attachment() {
	}

	public Attachment(BusinessCard businessCard, String path) {
		this.businessCard = businessCard;
		this.path = path;
	}

	public Attachment(BusinessCard businessCard, String path, String description) {
		this.businessCard = businessCard;
		this.path = path;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "attachment_id", unique = true, nullable = false)
	public Integer getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "business_card_business_card_id", nullable = false)
	public BusinessCard getBusinessCard() {
		return this.businessCard;
	}

	public void setBusinessCard(BusinessCard businessCard) {
		this.businessCard = businessCard;
	}

	@Column(name = "path", nullable = false, length = 150)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
