package com.edexer.model;

// Generated May 24, 2015 10:17:18 AM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BcRequest generated by hbm2java
 */
@Entity
@Table(name = "bc_request", catalog = "edexer_edexer", uniqueConstraints = @UniqueConstraint(columnNames = "reciver_user_id"))
public class BcRequest implements java.io.Serializable {

	private Integer bcRequestId;
	private BcRequestStatus bcRequestStatus;
	private User userBySenderUserId;
	private User userByReciverUserId;
	private Date sendDate;
	private String message;

	public BcRequest() {
	}

	public BcRequest(BcRequestStatus bcRequestStatus, User userBySenderUserId,
			User userByReciverUserId) {
		this.bcRequestStatus = bcRequestStatus;
		this.userBySenderUserId = userBySenderUserId;
		this.userByReciverUserId = userByReciverUserId;
	}

	public BcRequest(BcRequestStatus bcRequestStatus, User userBySenderUserId,
			User userByReciverUserId, Date sendDate, String message) {
		this.bcRequestStatus = bcRequestStatus;
		this.userBySenderUserId = userBySenderUserId;
		this.userByReciverUserId = userByReciverUserId;
		this.sendDate = sendDate;
		this.message = message;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bc_request_id", unique = true, nullable = false)
	public Integer getBcRequestId() {
		return this.bcRequestId;
	}

	public void setBcRequestId(Integer bcRequestId) {
		this.bcRequestId = bcRequestId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "req_status_id", nullable = false)
	public BcRequestStatus getBcRequestStatus() {
		return this.bcRequestStatus;
	}

	public void setBcRequestStatus(BcRequestStatus bcRequestStatus) {
		this.bcRequestStatus = bcRequestStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender_user_id", nullable = false)
	public User getUserBySenderUserId() {
		return this.userBySenderUserId;
	}

	public void setUserBySenderUserId(User userBySenderUserId) {
		this.userBySenderUserId = userBySenderUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reciver_user_id", unique = true, nullable = false)
	public User getUserByReciverUserId() {
		return this.userByReciverUserId;
	}

	public void setUserByReciverUserId(User userByReciverUserId) {
		this.userByReciverUserId = userByReciverUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_date", length = 19)
	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	@Column(name = "message", length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
