package com.edexer.model;

// Generated May 24, 2015 10:17:18 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * BusinessCard generated by hbm2java
 */
@Entity
@Table(name = "business_card", catalog = "edexer_edexer")
public class BusinessCard implements java.io.Serializable {

	private Integer businessCardId;
	private UserSubscription userSubscription;
	private String bcFirstName;
	private String middleName;
	private String bcLastName;
	private String birthDate;
	private String notes;
	private int creator;
	private String avatar;
	private Set mobiles = new HashSet(0);
	private Address address;
	private Set socialNetworks = new HashSet(0);
	private Set faxes = new HashSet(0);
	private Set tagses = new HashSet(0);
	private Set emails = new HashSet(0);
	private Set attachments = new HashSet(0);
	private Set websites = new HashSet(0);
	private Set ims = new HashSet(0);
	private Set titles = new HashSet(0);
	private Set bcPermissionses = new HashSet(0);
	private Set phones = new HashSet(0);

	public BusinessCard() {
	}

	public BusinessCard(int creator) {
		this.creator = creator;
	}

	public BusinessCard(UserSubscription userSubscription, String bcFirstName,
			String middleName, String bcLastName, String birthDate,
			String notes, int creator, String avatar, Set mobiles,
			Address address, Set socialNetworks, Set faxes, Set tagses,
			Set emails, Set attachments, Set websites, Set ims, Set titles,
			Set bcPermissionses, Set phones) {
		this.userSubscription = userSubscription;
		this.bcFirstName = bcFirstName;
		this.middleName = middleName;
		this.bcLastName = bcLastName;
		this.birthDate = birthDate;
		this.notes = notes;
		this.creator = creator;
		this.avatar = avatar;
		this.mobiles = mobiles;
		this.address = address;
		this.socialNetworks = socialNetworks;
		this.faxes = faxes;
		this.tagses = tagses;
		this.emails = emails;
		this.attachments = attachments;
		this.websites = websites;
		this.ims = ims;
		this.titles = titles;
		this.bcPermissionses = bcPermissionses;
		this.phones = phones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "business_card_id", unique = true, nullable = false)
	public Integer getBusinessCardId() {
		return this.businessCardId;
	}

	public void setBusinessCardId(Integer businessCardId) {
		this.businessCardId = businessCardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "subscription_user_id", referencedColumnName = "user_id"),
			@JoinColumn(name = "subscription_sub_type", referencedColumnName = "sub_type") })
	public UserSubscription getUserSubscription() {
		return this.userSubscription;
	}

	public void setUserSubscription(UserSubscription userSubscription) {
		this.userSubscription = userSubscription;
	}

	@Column(name = "bc_first_name", length = 50)
	public String getBcFirstName() {
		return this.bcFirstName;
	}

	public void setBcFirstName(String bcFirstName) {
		this.bcFirstName = bcFirstName;
	}

	@Column(name = "middle_name", length = 50)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "bc_last_name", length = 50)
	public String getBcLastName() {
		return this.bcLastName;
	}

	public void setBcLastName(String bcLastName) {
		this.bcLastName = bcLastName;
	}

	@Column(name = "birth_date", length = 50)
	public String getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(String birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "notes", length = 250)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "creator", nullable = false)
	public int getCreator() {
		return this.creator;
	}

	public void setCreator(int creator) {
		this.creator = creator;
	}

	@Column(name = "avatar", length = 200)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessCard")
	public Set getMobiles() {
		return this.mobiles;
	}

	public void setMobiles(Set mobiles) {
		this.mobiles = mobiles;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "businessCard")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessCard")
	public Set getSocialNetworks() {
		return this.socialNetworks;
	}

	public void setSocialNetworks(Set socialNetworks) {
		this.socialNetworks = socialNetworks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessCard")
	public Set getFaxes() {
		return this.faxes;
	}

	public void setFaxes(Set faxes) {
		this.faxes = faxes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "bc_tags", catalog = "edexer_edexer", joinColumns = { @JoinColumn(name = "bc_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "tags_id", nullable = false, updatable = false) })
	public Set getTagses() {
		return this.tagses;
	}

	public void setTagses(Set tagses) {
		this.tagses = tagses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessCard")
	public Set getEmails() {
		return this.emails;
	}

	public void setEmails(Set emails) {
		this.emails = emails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessCard")
	public Set getAttachments() {
		return this.attachments;
	}

	public void setAttachments(Set attachments) {
		this.attachments = attachments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessCard")
	public Set getWebsites() {
		return this.websites;
	}

	public void setWebsites(Set websites) {
		this.websites = websites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessCard")
	public Set getIms() {
		return this.ims;
	}

	public void setIms(Set ims) {
		this.ims = ims;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessCard")
	public Set getTitles() {
		return this.titles;
	}

	public void setTitles(Set titles) {
		this.titles = titles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessCard")
	public Set getBcPermissionses() {
		return this.bcPermissionses;
	}

	public void setBcPermissionses(Set bcPermissionses) {
		this.bcPermissionses = bcPermissionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessCard")
	public Set getPhones() {
		return this.phones;
	}

	public void setPhones(Set phones) {
		this.phones = phones;
	}

}
