package com.edexer.model;

// Generated May 24, 2015 10:17:18 AM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name = "email", catalog = "edexer_edexer")
public class Email implements java.io.Serializable {

	private EmailId id;
	private BusinessCard businessCard;

	public Email() {
	}

	public Email(EmailId id, BusinessCard businessCard) {
		this.id = id;
		this.businessCard = businessCard;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bcId", column = @Column(name = "bc_id", nullable = false)),
			@AttributeOverride(name = "emailAddress", column = @Column(name = "email_address", nullable = false, length = 150)) })
	public EmailId getId() {
		return this.id;
	}

	public void setId(EmailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bc_id", nullable = false, insertable = false, updatable = false)
	public BusinessCard getBusinessCard() {
		return this.businessCard;
	}

	public void setBusinessCard(BusinessCard businessCard) {
		this.businessCard = businessCard;
	}

}
