package com.edexer.model;

// Generated May 24, 2015 10:17:18 AM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Im generated by hbm2java
 */
@Entity
@Table(name = "im", catalog = "edexer_edexer")
public class Im implements java.io.Serializable {

	private ImId id;
	private BusinessCard businessCard;
	private String network;

	public Im() {
	}

	public Im(ImId id, BusinessCard businessCard, String network) {
		this.id = id;
		this.businessCard = businessCard;
		this.network = network;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "identifier", column = @Column(name = "identifier", nullable = false, length = 50)),
			@AttributeOverride(name = "bcId", column = @Column(name = "bc_id", nullable = false)) })
	public ImId getId() {
		return this.id;
	}

	public void setId(ImId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bc_id", nullable = false, insertable = false, updatable = false)
	public BusinessCard getBusinessCard() {
		return this.businessCard;
	}

	public void setBusinessCard(BusinessCard businessCard) {
		this.businessCard = businessCard;
	}

	@Column(name = "network", nullable = false, length = 50)
	public String getNetwork() {
		return this.network;
	}

	public void setNetwork(String network) {
		this.network = network;
	}

}
