package com.edexer.model;

// Generated May 24, 2015 10:17:18 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhoneId generated by hbm2java
 */
@Embeddable
public class PhoneId implements java.io.Serializable {

	private int bcId;
	private String phoneNum;

	public PhoneId() {
	}

	public PhoneId(int bcId, String phoneNum) {
		this.bcId = bcId;
		this.phoneNum = phoneNum;
	}

	@Column(name = "bc_id", nullable = false)
	public int getBcId() {
		return this.bcId;
	}

	public void setBcId(int bcId) {
		this.bcId = bcId;
	}

	@Column(name = "phone_num", nullable = false, length = 20)
	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhoneId))
			return false;
		PhoneId castOther = (PhoneId) other;

		return (this.getBcId() == castOther.getBcId())
				&& ((this.getPhoneNum() == castOther.getPhoneNum()) || (this
						.getPhoneNum() != null
						&& castOther.getPhoneNum() != null && this
						.getPhoneNum().equals(castOther.getPhoneNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBcId();
		result = 37 * result
				+ (getPhoneNum() == null ? 0 : this.getPhoneNum().hashCode());
		return result;
	}

}
