package com.edexer.model;

// Generated Feb 13, 2015 8:24:16 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubscriptionStatus generated by hbm2java
 */
@Entity
@Table(name = "subscription_status", catalog = "edexer")
public class SubscriptionStatus implements java.io.Serializable {

	private Integer subStatusId;
	private String subStatusName;
	private String desc;
	private Set userSubscriptions = new HashSet(0);

	public SubscriptionStatus() {
	}

	public SubscriptionStatus(String subStatusName) {
		this.subStatusName = subStatusName;
	}

	public SubscriptionStatus(String subStatusName, String desc,
			Set userSubscriptions) {
		this.subStatusName = subStatusName;
		this.desc = desc;
		this.userSubscriptions = userSubscriptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sub_status_id", unique = true, nullable = false)
	public Integer getSubStatusId() {
		return this.subStatusId;
	}

	public void setSubStatusId(Integer subStatusId) {
		this.subStatusId = subStatusId;
	}

	@Column(name = "sub_status_name", nullable = false, length = 50)
	public String getSubStatusName() {
		return this.subStatusName;
	}

	public void setSubStatusName(String subStatusName) {
		this.subStatusName = subStatusName;
	}

	@Column(name = "desc", length = 50)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriptionStatus")
	public Set getUserSubscriptions() {
		return this.userSubscriptions;
	}

	public void setUserSubscriptions(Set userSubscriptions) {
		this.userSubscriptions = userSubscriptions;
	}

	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof SubscriptionStatus))
			return false;
		if (this.getSubStatusId() == ((SubscriptionStatus) obj)
				.getSubStatusId())
			return true;
		return false;
	}

}
