package com.edexer.model;

// Generated May 24, 2015 10:17:18 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WebsiteId generated by hbm2java
 */
@Embeddable
public class WebsiteId implements java.io.Serializable {

	private String website;
	private int bcId;

	public WebsiteId() {
	}

	public WebsiteId(String website, int bcId) {
		this.website = website;
		this.bcId = bcId;
	}

	@Column(name = "website", nullable = false, length = 150)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "bc_id", nullable = false)
	public int getBcId() {
		return this.bcId;
	}

	public void setBcId(int bcId) {
		this.bcId = bcId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WebsiteId))
			return false;
		WebsiteId castOther = (WebsiteId) other;

		return ((this.getWebsite() == castOther.getWebsite()) || (this
				.getWebsite() != null && castOther.getWebsite() != null && this
				.getWebsite().equals(castOther.getWebsite())))
				&& (this.getBcId() == castOther.getBcId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getWebsite() == null ? 0 : this.getWebsite().hashCode());
		result = 37 * result + this.getBcId();
		return result;
	}

}
