package com.edexer.model;

// Generated Feb 13, 2015 8:24:16 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subscription generated by hbm2java
 */
@Entity
@Table(name = "subscription", catalog = "edexer")
public class Subscription implements java.io.Serializable {

	private Integer subscriptionId;
	private String subscriptionTypeName;
	private String desc;
	private Set userSubscriptions = new HashSet(0);

	public Subscription() {
	}

	public Subscription(String subscriptionTypeName) {
		this.subscriptionTypeName = subscriptionTypeName;
	}

	public Subscription(String subscriptionTypeName, String desc,
			Set userSubscriptions) {
		this.subscriptionTypeName = subscriptionTypeName;
		this.desc = desc;
		this.userSubscriptions = userSubscriptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "subscription_id", unique = true, nullable = false)
	public Integer getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(Integer subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	@Column(name = "subscription_type_name", nullable = false, length = 50)
	public String getSubscriptionTypeName() {
		return this.subscriptionTypeName;
	}

	public void setSubscriptionTypeName(String subscriptionTypeName) {
		this.subscriptionTypeName = subscriptionTypeName;
	}

	@Column(name = "desc", length = 100)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscription")
	public Set getUserSubscriptions() {
		return this.userSubscriptions;
	}

	public void setUserSubscriptions(Set userSubscriptions) {
		this.userSubscriptions = userSubscriptions;
	}

	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Subscription))
			return false;
		if (this.getSubscriptionId() == ((Subscription) obj)
				.getSubscriptionId())
			return true;
		return false;
	}

}
